2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_setup.py:_flush():69] setting env: {'project': 'exercise_14', 'run_group': 'dev'}
2024-01-14 09:55:20,478 WARNING MainThread:63866 [wandb_setup.py:_flush():69] could not save program above cwd: /Users/jchan/miniconda3/envs/mlflow-7398531e5288219e428182dc4d6601ae57991d39/bin/pytest
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_setup.py:_flush():69] setting login settings: {}
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_init.py:_log_setup():334] Logging user logs to /Users/jchan/Documents/projects/udacity/genre_classification/check_data/wandb/run-20240114_095520-2za0ncsw/logs/debug.log
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/jchan/Documents/projects/udacity/genre_classification/check_data/wandb/run-20240114_095520-2za0ncsw/logs/debug-internal.log
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_init.py:init():367] calling init triggers
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2024-01-14 09:55:20,478 INFO    MainThread:63866 [wandb_init.py:init():416] starting backend
2024-01-14 09:55:20,478 INFO    MainThread:63866 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-14 09:55:20,487 INFO    MainThread:63866 [backend.py:ensure_launched():123] starting backend process...
2024-01-14 09:55:20,490 INFO    MainThread:63866 [backend.py:ensure_launched():127] started backend process with pid: 63878
2024-01-14 09:55:20,491 INFO    MainThread:63866 [wandb_init.py:init():421] backend started and connected
2024-01-14 09:55:20,493 INFO    MainThread:63866 [wandb_init.py:init():461] updated telemetry
2024-01-14 09:55:20,493 INFO    MainThread:63866 [wandb_init.py:init():480] communicating current version
2024-01-14 09:55:20,920 INFO    MainThread:63866 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.16.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-14 09:55:20,920 INFO    MainThread:63866 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2024-01-14 09:55:21,307 INFO    MainThread:63866 [wandb_init.py:init():518] starting run threads in backend
2024-01-14 09:55:21,351 INFO    MainThread:63866 [wandb_run.py:_console_start():1476] atexit reg
2024-01-14 09:55:21,351 INFO    MainThread:63866 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.REDIRECT
2024-01-14 09:55:21,351 INFO    MainThread:63866 [wandb_run.py:_redirect():1344] Redirecting console.
2024-01-14 09:55:21,351 INFO    MainThread:63866 [redirect.py:install():213] install start
2024-01-14 09:55:21,351 INFO    MainThread:63866 [redirect.py:install():228] install stop
2024-01-14 09:55:21,352 INFO    MainThread:63866 [redirect.py:install():213] install start
2024-01-14 09:55:21,352 INFO    MainThread:63866 [redirect.py:install():228] install stop
2024-01-14 09:55:21,352 INFO    MainThread:63866 [wandb_run.py:_redirect():1390] Redirects installed.
2024-01-14 09:55:21,352 INFO    MainThread:63866 [wandb_init.py:init():542] run started, returning control to user process
2024-01-14 09:55:24,118 INFO    MainThread:63866 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2024-01-14 09:55:24,118 INFO    MainThread:63866 [wandb_run.py:_restore():1418] restore
2024-01-14 09:55:24,118 INFO    MainThread:63866 [redirect.py:uninstall():232] uninstall start
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():287] _stop: stdout
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():293] _stop closed: stdout
2024-01-14 09:55:24,119 INFO    stdout    :63866 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2024-01-14 09:55:24,119 INFO    stdout    :63866 [redirect.py:_pipe_relay():145] relay done done: stdout
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():299] _stop joined: stdout
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():301] _stop rd closed: stdout
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:uninstall():236] uninstall done
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:uninstall():232] uninstall start
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():287] _stop: stderr
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():293] _stop closed: stderr
2024-01-14 09:55:24,119 INFO    stderr    :63866 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2024-01-14 09:55:24,119 INFO    stderr    :63866 [redirect.py:_pipe_relay():145] relay done done: stderr
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():299] _stop joined: stderr
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:_stop():301] _stop rd closed: stderr
2024-01-14 09:55:24,119 INFO    MainThread:63866 [redirect.py:uninstall():236] uninstall done
2024-01-14 09:55:24,417 INFO    MainThread:63866 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 989
  total_bytes: 989
}

2024-01-14 09:55:26,428 INFO    MainThread:63866 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 58016
  total_bytes: 58016
}

2024-01-14 09:55:27,514 INFO    MainThread:63866 [wandb_run.py:_show_files():1790] logging synced files
